### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by ckuenne** [lulab/COME#1]
Hi, I was unable to download feature vectors or models from either of your presented links (onedrive, baidu).

**Comment by lulab** [comment]
Thank you for pointing that out.

Long, do you still have the files? Can you update it with a new baidu or
onedrive link?
Thanks.

Sincerely,
John

------
Zhi John Lu   |  鲁 志
MOE Key Lab of Bioinformatics
School of Life Sciences, Tsinghua University
Beijing 100084, China
http://ncrnalab.org/ <http://www.ncrnalab.org/>

**Comment by lulab** [comment]
Dear User,

We have updated the downloading links. Please check.

Sincerely,
John

------
Zhi John Lu   |  鲁 志
MOE Key Lab of Bioinformatics
School of Life Sciences, Tsinghua University
Beijing 100084, China
http://ncrnalab.org/ <http://www.ncrnalab.org/>

**Comment by ckuenne** [comment]
Hi,

works, thanks!

Best,
Carsten

**Comment by jilguero888** [comment]
The links are dead again. May you please post updated links?.

Also, what about non-model organisms?. Can you train the program?.

**Comment by lulab** [comment]
Download link has been updated in Readme:  https://cloud.tsinghua.edu.cn/d/915bcc7123f54244b41d/
